name: .NET

on:
  workflow_dispatch:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Git Config
      run: git config --global user.email "git@example.com" && git config --global user.name "Builder"
    
    - name: Patch
      run: cd libamiibo && git am ../0001-Don-t-use-appsettings.json.patch
    
    - name: Build
      run: msbuild amiigen.sln
    
    - name: Publish build artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: amiigen-debug
        path: amiigen\bin\Debug\net461
